slide_file: /data/DeepLearning/mehdi/csv/luminal_data_split.csv
patch_size: 1024 #768
level: 0
noted : True
balance : True
fold_id: 0

transform: True 
num_classes : 3
normalize: False
horovod: False
center_crop : 0
gpu: 0
num_workers: 8


dropout : 0.5
logfolder: /data/DeepLearning/mehdi/log
model: resnet50_ #resnet50_ efficientnet #vanilla #vit inception_v3 #[vanilla,"resnet",mobilenet]
freeze : False
pretrained : True
loss: ce
epochs: 20
batch_size: 8
lr: 0.001
wd: 0.0001
scheduler: one-cycle #["one-cycle", "cosine-anneal", "reduce-on-plateau"]
group_norm: False
grad_accumulation: 1
ckpt_path : 