model: resnet #["resnet"]
slide_file: /data/DeepLearning/mehdi/csv/luminal_data_split.csv
loss: bce
logfolder: /data/DeepLearning/mehdi/log"
gpu: 0
horovod: False
batch_size: 8
lr:
wd: 0.001
epochs: 10
patch_size: 1024
num_worker: 4
group_norm: True
scheduler: reduce-on-plateau #["one-cycle", "cosine-anneal", "reduce-on-plateau"]
grad_accumulation: 1
transforms: True
