model: resnet #vit #[vanilla,"resnet",mobilenet]
slide_file: /data/DeepLearning/mehdi/csv/luminal_data_split.csv
loss: ce
logfolder: /data/DeepLearning/mehdi/log
gpu: 0
horovod: False
batch_size: 32
lr: 0.0004
wd: 0.001
epochs: 40
patch_size: 1024
num_workers: 8
group_norm: False
scheduler: cosine-anneal #["one-cycle", "cosine-anneal", "reduce-on-plateau"]
grad_accumulation: 1
transform: True 
noted : True
freeze : False
pretrained : True
level: 0
normalize: False
num_classes : 3