slide_file: /data/DeepLearning/mehdi/csv/luminal_data_split.csv
patch_size: 512 #768
level: 1
noted : True
balance : True


transform: True 
num_classes : 3
normalize: False
horovod: False
center_crop : 0
gpu: 1
num_workers: 8


dropout : 0.5
logfolder: /data/DeepLearning/mehdi/log
model: vanilla #vit #[vanilla,"resnet",mobilenet]
freeze : False
pretrained : True
loss: ce
epochs: 30
batch_size: 64
lr: 0.001
wd: 0.01
scheduler: one-cycle #["one-cycle", "cosine-anneal", "reduce-on-plateau"]
group_norm: False
grad_accumulation: 1