model: vanilla #[vanilla,"resnet"]
slide_file: /data/DeepLearning/mehdi/csv/luminal_data_split.csv
loss: bce
logfolder: /data/DeepLearning/mehdi/log
gpu: 0
horovod: False
batch_size: 64
lr: 0.0001
wd: 0.001
epochs: 10
patch_size: 1024
num_workers: 8
group_norm: False
scheduler: one-cycle #["one-cycle", "cosine-anneal", "reduce-on-plateau"]
grad_accumulation: 1
transform: True 
