GEOMETRIES = [
    "area",
    "gd_ax",
    "pt_ax",
    "length",
    "compactness",
    "eliptic_fit",
    "enclosing_circle_overlap",
    "length_width_ratio",
    "Eccentricity",
    "smoothmess",
    "convex_area",
    "iou",
]

COLORS = [
    "normalized_red_intensity",
    "normalized_green_intensity",
    "normalized_blue_intensity",
    "h_mean",
    "e_mean",
    "h_std",
    "e_std",
    "hue_mean",
    "hue_std",
    "saturation_mean",
    "value_hsv_mean",
    "saturation_std",
    "value_hsv_std",
]
TEXTURES = [
    "hu_0",
    "hu_1",
    "hu_2",
    "hu_3",
    "hu_4",
    "hu_5",
    "hu_6",
    "Angular Second Moment",
    "Contrast",
    "Correlation",
    "Sum of Squares: Variance",
    "Inverse Difference Moment",
    "Sum Average",
    "Sum Variance",
    "Sum Entropy",
    "Entropy",
    "Difference Variance",
    "Difference Entropy",
    "Information Measure of Correlation 1",
    "Information Measure of Correlation 2",
]
GEOMETRIES_SLIDE = [
    "('area', 'area_mean')",
    "('area', 'area_std')",
    "gd_ax_mean",
    "pt_ax_mean",
    "length_mean",
    "compactness_mean",
    "eliptic_fit_mean",
    "enclosing_circle_overlap_mean",
    "length_width_ratio_mean",
    "Eccentricity_mean",
    "smoothmess_mean",
    "convex_area_mean",
    "iou_mean",
    "gd_ax_std",
    "pt_ax_std",
    "length_std",
    "compactness_std",
    "eliptic_fit_std",
    "enclosing_circle_overlap_std",
    "length_width_ratio_std",
    "Eccentricity_std",
    "smoothmess_std",
    "convex_area_std",
    "iou_std",
]

COLORS_SLIDE = [
    "normalized_red_intensity_mean",
    "normalized_green_intensity_mean",
    "normalized_blue_intensity_mean",
    "h_mean_mean",
    "e_mean_mean",
    "h_std_mean",
    "e_std_mean",
    "hue_mean_mean",
    "hue_std_mean",
    "saturation_mean_mean",
    "value_hsv_mean_mean",
    "saturation_std_mean",
    "value_hsv_std_mean",
    "normalized_red_intensity_std",
    "normalized_green_intensity_std",
    "normalized_blue_intensity_std",
    "h_mean_std",
    "e_mean_std",
    "h_std_std",
    "e_std_std",
    "hue_mean_std",
    "hue_std_std",
    "saturation_mean_std",
    "value_hsv_mean_std",
    "saturation_std_std",
    "value_hsv_std_std",
]
TEXTURES_SLIDE = [
    "hu_0_mean",
    "hu_1_mean",
    "hu_2_mean",
    "hu_3_mean",
    "hu_4_mean",
    "hu_5_mean",
    "hu_6_mean",
    "Angular Second Moment_mean",
    "Contrast_mean",
    "Correlation_mean",
    "Sum of Squares: Variance_mean",
    "Inverse Difference Moment_mean",
    "Sum Average_mean",
    "Sum Variance_mean",
    "Sum Entropy_mean",
    "Entropy_mean",
    "Difference Variance_mean",
    "Difference Entropy_mean",
    "Information Measure of Correlation 1_mean",
    "Information Measure of Correlation 2_mean",
    "hu_0_std",
    "hu_1_std",
    "hu_2_std",
    "hu_3_std",
    "hu_4_std",
    "hu_5_std",
    "hu_6_std",
    "Angular Second Moment_std",
    "Contrast_std",
    "Correlation_std",
    "Sum of Squares: Variance_std",
    "Inverse Difference Moment_std",
    "Sum Average_std",
    "Sum Variance_std",
    "Sum Entropy_std",
    "Entropy_std",
    "Difference Variance_std",
    "Difference Entropy_std",
    "Information Measure of Correlation 1_std",
    "Information Measure of Correlation 2_std",
]

DISTRIBUTIONS_SLIDE = [
    "('dist_mean', 'dist_mean_mean')",
    "('dist_mean', 'dist_mean_std')",
    "lymph_v_tum",
    "cellularite_tumoral",
    "cellularite_tumoral_big",
    "cellularite_tumoral_mid",
    "cellularite_tumoral_small",
    "part_tum_petit_0",
    "part_tum_petit_1",
    "part_tum_mid_0",
    "part_tum_mid_1",
    "part_tum_big_0",
    "part_lymph_0",
    "part_lymph_1",
    "cellularite_lympho",
]

IHC = [
    "rp_intensite_cat",
    "re_intensite_cat",
    "re_pct",
    "rp_pct",
    "ki67",
]

CCPU = [
    "taille",
    "ee_mitoses",
    "ee_mitoses_par_mm2",
    "ee_architecture",
    "ee_noyaux",
    "nb_ggl_pos",
    "nb_ggl_rc",
    "pN_cat",
]

LYMPHOCYTE = [
    "gd_ax",
    "compactness",
    "eliptic_fit",
    "enclosing_circle_overlap",
    "area",
    "smoothmess",
]

TRASH = [
    "gd_ax",
    "pt_ax",
    "compactness",
    "eliptic_fit",
    "enclosing_circle_overlap",
    "area",
    "length_width_ratio",
    "Eccentricity",
    "smoothmess",
    "iou",
]


EPSILON = 1e-9
